spring.application.name=backend
server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/expensetracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bnz@#1010#}
spring.jpa.hibernate.ddl-auto=update

